villainy_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: 'sessions#new'

  resources :users, only: [:new, :create, :index, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :prisoners, :prisons

  get "prisons/:id/prisoners", to: 'prisons#prisoners_by_prison'

end

villainy_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

villainy_app/app/models/prison.rb
class Prison < ApplicationRecord
  belongs_to :user

    has_many :prisoners


  validates_presence_of :number
end

villainy_app/app/models/prisoner.rb
class Prisoner < ApplicationRecord
  belongs_to :prison

  validates_presence_of :name, :description, :image_url
end

villainy_app/app/models/user.rb
class User < ApplicationRecord
      PASSWORD_LENGTH = (6..25)
  USERNAME_LENGTH = (5..15)

  validates_presence_of :username
  validates :username, length: USERNAME_LENGTH, uniqueness: true

  validates :password, length: PASSWORD_LENGTH, allow_nil: true

  has_many :prisons
  has_many :prisoners


  attr_reader :password

  def self.find_from_credentials(username, password)
    user = find_by(username: username)
    return nil unless user
    user if user.is_password?(password)
  end

  def is_password?(password_attempt)
    BCrypt::Password.new(password_digest).is_password?(password_attempt)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end


end

villainy_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user


  private

  def sign_in(user)
    session[:session_token] = SecureRandom.urlsafe_base64
    user.update!(session_token: session[:session_token])
  end

  def sign_out
    return unless current_user
    current_user.update!(session_token: nil)
    session.delete(:session_token)
  end

  def current_user
    @current_user ||= find_current_user
  end

  def find_current_user
    session_token = session[:session_token]
    session_token && User.find_by(session_token: session_token)
  end

  def ensure_signed_in
    return if current_user
    flash[:error] = 'you must be signed in to see this'
    redirect_to :root
  end

  def ensure_signed_out
    return unless current_user
    flash[:error] = 'you are already signed in'
    redirect_to users_path
  end
end

villainy_app/app/controllers/prisoners_controller.rb
class PrisonersController < ApplicationController

  before_action :ensure_signed_in
  before_action :load_prisoner, only: [:show, :edit, :update, :destroy]

  def new
    @prisoner = Prisoner.new
  end

  def create
    @prisoner = Prisoner.new(create_params)
    @prisoner.user_id = current_user.id

    if @prisoner.save
      flash[:notice] = 'Prisoner has been locked away!'
      redirect_to prisoner_path(@prisoner)
    else
      flash[:error] = @prisoner.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit
  end

  def update
    if @prisoner.update(update_params)
      flash[:notice] = 'Prisoner file updated!'
      redirect_to prisoner_path(@prisoner)
    else
      flash[:error] = @prisoner.errors.full_messages.join(', ')
      render :edit
    end
  end

  def index
    @prisoners = current_user.prisoners
  end

  def show
  end

  def destroy
    @prisoner.destroy!

    flash[:notice] = "#{@prisoner.name} has made bail!"
    redirect_to prisoners_path
  end

  private

  def create_params
    params.require(:prisoner).permit(:name, :description, :image_url, :prison_id)
  end

  def update_params
    params.require(:prisoner).permit(:description)
  end

  def load_prisoner
    @prisoner = current_user.prisoners.find(params[:id])
  end
end

villainy_app/app/controllers/prisons_controller.rb
class PrisonsController < ApplicationController

  before_action :ensure_signed_in
  before_action :load_prison, only: [:show, :edit, :update, :destroy]

  def new
    @prison = Prison.new
  end

  def prisoners_by_prison 
    @prison = Prison.find(params[:id])
    

  end

  def create
      @prison = Prison.new(create_params)
      @prison.user = current_user


      if @prison.save
      flash[:notice] = 'Prison created!'
      redirect_to prison_path(@prison)
    else
      flash[:error] = @prison.errors.full_messages.join(', ')
      render :new
    end

  end

  def edit
  end


  def update
    if @prison.update(update_params)
      flash[:notice] = 'Prison updated!'
      redirect_to prison_path(@prison)
    else
      flash[:error] = @prison.errors.full_messages.join(', ')
      render :edit
    end
  end

  def index
    @prisons = current_user.prisons
  end

  def show
  end

  def destroy
    @prison.destroy!

    flash[:notice] = "#{@prison.number} has been shut down due to insufficient funding!"
    redirect_to prisons_path
  end

  private

  def create_params
    params.require(:prison).permit(:number)
  end

  def update_params
    params.require(:prison).permit(:number)
  end

  def load_prison
    @prison = current_user.prisons.find(params[:id])
  end
end

villainy_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :ensure_signed_out, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    username = user_params[:username]
    password = user_params[:password]

    user = User.find_from_credentials(username, password)

    if user
      sign_in(user)
      flash[:notice] = "Hi, Warden #{username}! You signed in!"
      redirect_to users_path
    else
      flash[:error] = "Warden not found :("
      @user = User.new(username: username)
      render :new
    end
  end

  def destroy
    sign_out
    flash[:notice] = 'You signed out!'
    redirect_to new_session_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

villainy_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :ensure_signed_out, only: [:new, :create]
  before_action :ensure_signed_in, only: [:show, :index]

  def new
    @user = User.new
  end

  def create
    @user = User.new(create_params)

    if @user.save
      sign_in(@user)
      flash[:notice] = 'You are signed in!'
      redirect_to users_path
    else
      flash[:error] = @user.errors.full_messages.join(', ')
      render :new
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def create_params
    params.require(:user).permit(:username, :password)
  end
end

villainy_app/app/helpers/application_helper.rb
module ApplicationHelper
end

villainy_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Villainy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">Villainy app</div>

    <% if current_user %>
      <%= link_to current_user.username, user_path(current_user) %> signed in
      <%= button_to 'Log out', session_path, method: :delete %>
    <% end %>

    <% if flash[:notice].present? %>
      <div class="notice">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <% if flash[:error].present? %>
      <div class="errors">
        <b>Errors:</b>

        <%= flash[:error] %>
      </div>
    <% end %>

    <%= yield %>


    <% if current_user %>
      <br><br>
      <%= link_to 'Prisons', prisons_path %>
      |
      <%= link_to 'Build Prison', new_prison_path %>
      |
      <%= link_to 'Create Prisoner', new_prisoner_path %>
    <% end %>

    <div class="footer"></div>
  </body>
</html>

villainy_app/app/views/prisoners/edit.html.erb
<h2>Update Prisoner file</h2>

<%= form_for @prisoner do |form| %>

  <%= label_tag :name %>

  <b><%= @prisoner.name %></b>
  <br>
  <%= label_tag :description %>
  <br>
  <%= form.text_area :description, placeholder: 'Description' %>
    <br>

  <%= label_tag :image_url %>
      <br>
  <%= form.text_field :image_url, placeholder: 'Image' %>
  
  <br>
  <%= submit_tag 'Update file!' %>
<% end %>

villainy_app/app/views/prisoners/index.html.erb
<h2>Prisoners</h2>

<% if @prisoners.empty? %>
  Stop slacking and start locking up some criminals!!!!

<% else %>
  <ul>
    <% @prisoners.each do |prisoner| %>
      <li><%= link_to prisoner.name, prisoner_path(prisoner) %></li>
    <% end %>
  </ul>
<% end %>

villainy_app/app/views/prisoners/new.html.erb
<h2>Lock up a prisoner</h2>

<%= form_for @prisoner do |form| %>
  <%= form.text_field :name, placeholder: 'Name' %>
  <br>
  <%= form.text_area :description, placeholder: 'Description' %>
    <br>
  <%= form.text_field :image_url, placeholder: 'Image' %>

  <br>
  <%= form.text_field :prison_id, placeholder: 'Prison ID' %>
    <br>

  <%= submit_tag 'Lock up!' %>
<% end %>

villainy_app/app/views/prisoners/show.html.erb
<h2><%= @prisoner.name %></h2>

Description:
<p><i><%= @prisoner.description %></i></p>
<img src="<%= @prisoner.image_url%>" style="max-height: 400px; max-width: 400px;">

<br>
<%= button_to 'Release prisoner', prisoner_path(@prisoner), method: :delete %>
<br>
<%= link_to 'Edit prisoner file', edit_prisoner_path(@prisoner) %>
<br>

villainy_app/app/views/prisons/edit.html.erb
<h2>Update Prison</h2>

<%= form_for @prison do |form| %>

  <%= label_tag :number %>

  <br>

  <%= form.text_area :number, placeholder: 'Number' %>

  <br>
  <%= submit_tag 'Update Prison!' %>
<% end %>

villainy_app/app/views/prisons/index.html.erb
<h2>Prisons</h2>
<% @prisons.each do |prison| %>  

<% if @prisons.empty? %>
  Build a prison to get started

<% else %>
<ul>
    <li><%= link_to "Prison: #{prison.number}", "#{prison_path(prison)}/prisoners" %></li>
      <%= button_to 'Close prison', "prisons/#{prison.id}", method: :delete %>

    <% end %>
  
</ul>

<% end %>

villainy_app/app/views/prisons/new.html.erb
<h2>Create a prison!</h2>

<%= form_for @prison do |form| %>
  <%= form.text_field :number, placeholder: 'Number' %>
  
  <br>
  <%= submit_tag 'Build Prison!' %>
<% end %>

villainy_app/app/views/prisons/prisoners_by_prison.html.erb
<% @prison.prisoners.each do |prisoner|%>


<h2><%= link_to prisoner.name, prisoner_path(prisoner)%></h2>
<img src="<%= prisoner.image_url%>" style="max-height: 300px; max-width: 300px;">



<% end %>

villainy_app/app/views/prisons/show.html.erb
<h2>Prison number: <%= @prison.number %></h2>




<%= button_to 'Close prison', prison_path(@prison), method: :delete %>
<br>

villainy_app/app/views/users/new.html.erb
<h2> Create an account </h2>

<%= form_for @user do |form| %>
  <%= form.text_field :username,
        placeholder: 'Username',
        required: true,
        minlength: User::USERNAME_LENGTH.begin,
        maxlength: User::USERNAME_LENGTH.end
  %>

  <%= form.password_field :password,
        placeholder: 'password',
        required: true,
        minlength: User::PASSWORD_LENGTH.begin,
        maxlength: User::PASSWORD_LENGTH.end
  %>

  <%= submit_tag 'Create Account!' %>
<% end %>

<br>
Returning user? <%= link_to 'Sign in', new_session_path %>

villainy_app/app/views/users/show.html.erb
<br>
<br>
<h1> Welcome back, Warden <%= @user.username %></h1>

<br>